name: ios
on: push

jobs: 
  build:
    name: "iOS test"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Select Xcode"
        run: sudo xcode-select -s /Applications/Xcode_12.4.app/Contents/Developer
      - name: "Install xcpretty"
        run: gem install xcpretty
      - name: "Remove DerivedData"
        run: rm -rf /Users/runner/Library/Developer/Xcode/DerivedData/
      - name: Xcode Build
        run: |
          set -o pipefail &&
          xcodebuild 
          -project SpmConfigurationExamination.xcodeproj
          -sdk iphonesimulator
          -scheme SpmConfigurationExamination
          -configuration Debug
          clean build | xcpretty
